# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17746e2aa6f9a5a2e78f273d925c5274df9d61f0bbed26750c08bb959b4b21ec330b9497886ca56004050c306af3f5efeee585f287be8feea3fc3759e3f071a

test:
  secret_key_base: 8297c32634561437c814ee88261fd8f359141a5e3cf68ab884f0c91eb0219b3c1995e46b62c02012639d38da9a1f6d00fc80d4e6c7faeaac063febc570fb00be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
